# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "latestw_all" ]
  pull_request:
    branches: [ "latestw_all" ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1.3
      with:
        # Folder location of where vswhere.exe is located if a self-hosted agent
        # vswhere-path: # optional
        # Version of Visual Studio to search; defaults to latest if not specified
        # vs-version: # optional
        # Enable searching for pre-release versions of Visual Studio/MSBuild
        # vs-prerelease: # optional
        # The preferred processor architecture of MSBuild. Can be either "x86" or "x64". "x64" is only available from Visual Studio version 17.0 and later.
        msbuild-architecture: x64 # optional, default is x86
    - name: Setup Windows 10 SDK Action
      uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.9
      with:
        # SDK 5-digit version to install (e.g 17763, 18362, 19041)
        sdk-version: 17763
    - name: Build
      run: |
        ipmo .\contrib\win32\openssh\OpenSSHBuildHelper.psm1 -Force
        Start-OpenSSHBuild -Configuration Release -NativeHostArch x64

